name: Test
on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    # - name: Set Timezone
    #   uses: szenius/set-timezone@v1.0
    #   with:
    #     timezoneLinux: America/Denver

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ruby 3.1.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2

    - name: Cache ruby gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ubuntu-20-04-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ubuntu-20-04-gems-

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ubuntu-20-04-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ubuntu-20-04-modules-

    - name: Install ruby dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Install js dependencies
      run: |
        yarn install --pure-lockfile

    - name: Install postgres dependency
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Set up the database
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: |
        cp config/database.yml .example
        bundle exec rails db:create
        bundle exec rails db:migrate

    - name: Run specs
      env:
        PGHOST: 127.0.0.1
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        COVERAGE: '1'
      run: bundle exec rspec

    - name: Upload coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage

  coverage:
    runs-on: ubuntu-latest
    needs: rspec

    steps:
    - name: Download coverage report
      uses: actions/download-artifact@v2
      with:
        name: coverage-report
        path: coverage

    - name: Check coverage
      uses: vigetlabs/simplecov-check@1.0
      with:
        minimum_coverage: 100
        coverage_path: coverage/.last_run.json


# Eventually, define a `deploy` job dependent on `coverage`
#
# - name: Install SSH deploy key
#   if: ${{ github.ref == 'refs/heads/main' }}
#   env:
#     DEPLOY_KEY: ${{ secrets.CI_DEPLOY_KEY }}
#   run: |
#     mkdir -p ~/.ssh
#     chmod 700 ~/.ssh
#     echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
#     chmod 600 ~/.ssh/id_rsa
#     ssh-keyscan staging.portal.fmaalerts.com > ~/.ssh/known_hosts
#
# - name: Deploy
#   if: ${{ github.ref == 'refs/heads/main' }}
#   run: |
#     bundle exec cap staging deploy
